### ISSUE TITLE
Exception: HTTP Error: 400 running 'todoist ls tod'

### ISSUE THREAD

**Issue by shedali** [krydos/todoist-cli#1]
The other commands are working great.

todoist ls tod

```
Traceback (most recent call last):
  File "/home/todoist-cli/todoist.py", line 105, in <module>
    json_tasks = json.loads(todoist.getTodayTasks())
  File "/home/todoist-cli/todoist.py", line 30, in getTodayTasks
    return t.query({"tod"});
  File "/home/todoist-cli/todoist_functions.py", line 111, in query
    return self._fetch("query", dict(queries=queries, as_count=Processors.bool2int(as_count)))
  File "/home/todoist-cli/todoist_functions.py", line 146, in _fetch
    raise Exception("HTTP Error: %s" % e.code)
Exception: HTTP Error: 400
```

**Comment by krydos** [comment]
Wow... I thought nobody needs this project :)

This project is not done but I will take a look and will try to fix it. Thanks :)

**Comment by shedali** [comment]
I think many people would appreciate a command line interface to todoist, thanks for sharing! Happy to test...

**Comment by ayancey** [comment]
Hi. Problem still occurs, it looks like?

```
Traceback (most recent call last):
  File "todoist.py", line 105, in <module>
    json_tasks = json.loads(todoist.getTodayTasks())
  File "todoist.py", line 30, in getTodayTasks
    return t.query({"tod"});
  File "D:\Downloads\todoist-cli-master\todoist-cli-master\todoist_functions.py"
, line 111, in query
    return self._fetch("query", dict(queries=queries, as_count=Processors.bool2i
nt(as_count)))
  File "D:\Downloads\todoist-cli-master\todoist-cli-master\todoist_functions.py"
, line 156, in _fetch
    raise UnexpectedResult(res)
todoist_functions.UnexpectedResult
```

**Comment by krydos** [comment]
Hi Guys,
Todoist introduced Python library which implements API of the service. You can take a look [HERE](https://github.com/Doist/todoist-api). I think I will use it in this project. So it will be completely rewritten soon. I hope I will find a time for this. Sorry about this. 

I will be so happy if someone can help me with it. Or maybe if you don't like Python we can try to use different language.

**Comment by ayancey** [comment]
@KryDos Thanks for the response. I ended up using https://github.com/ddksr/cliist, which met my needs.

**Comment by krydos** [comment]
Wow, awesome. Thanks, @ayancey, for the link. I think I will try to use this client too :)
